/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.HoaDonNhapNguyenLieuDAO;
import control.NguyenLieuDAO;
import control.NhaCungCapDAO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.HoaDonNhapNguyenLieu;
import model.NhaCungCap;

/**
 *
 * @author Hazard
 */
public class ListNhaCungCapFrm extends javax.swing.JFrame {

    static private ArrayList<NhaCungCap> list1;
    static private ArrayList<HoaDonNhapNguyenLieu> list2;
    /**
     * Creates new form ListNhaCungCap
     */
    public ListNhaCungCapFrm(ArrayList<NhaCungCap> list1, ArrayList<HoaDonNhapNguyenLieu> list2) throws ClassNotFoundException, SQLException {
        this.list1=list1;
        this.list2 = list2;
        initComponents();
        //showHoaDonNhapInfor();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tieuDe = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        HoaDonNhapTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        note = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tieuDe.setText("Danh sách các nhà cung cấp");

        jScrollPane1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jScrollPane1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        HoaDonNhapTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "mã nhà cung cấp", "tên nhà cung cấp", "tổng số lượng nguyên liệu", "tổng số tiền"
            }
        ));
        HoaDonNhapTable.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                HoaDonNhapTableAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        HoaDonNhapTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HoaDonNhapTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(HoaDonNhapTable);

        jButton1.setText("Quay lại");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        note.setText("*Click vào 1 dòng để xem chi tiết nhà cung cấp");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(tieuDe))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(note)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tieuDe)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(note)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jScrollPane1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jScrollPane1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1AncestorAdded

    private void HoaDonNhapTableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_HoaDonNhapTableAncestorAdded
        // TODO add your handling code here:
        
        ArrayList<NhaCungCap> listNhaCungCapByID = null;
        listNhaCungCapByID =this.list1;
        ArrayList<HoaDonNhapNguyenLieu> listHoaDonNhapNguyenLieu = null;
        listHoaDonNhapNguyenLieu = this.list2;
        DefaultTableModel defaultTableModel = (DefaultTableModel) HoaDonNhapTable.getModel();
        Object[] row = new Object[4];
        for (int i = 0; i < listHoaDonNhapNguyenLieu.size(); i++) {
            row[0] = listHoaDonNhapNguyenLieu.get(i).getIDnhaCungCap();
            row[1] = listNhaCungCapByID.get(i).getTen();
            row[2] = listHoaDonNhapNguyenLieu.get(i).getSoLuong();
            row[3] = listHoaDonNhapNguyenLieu.get(i).getTongTien();
            defaultTableModel.addRow(row);
        }
        //NguyenLieuDAO nguyenLieuDAO = new NguyenLieuDAO(list2);
    }//GEN-LAST:event_HoaDonNhapTableAncestorAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            new ListNhaCungCapFrm(list1, list2).setVisible(false);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ListNhaCungCapFrm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ListNhaCungCapFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
        ThongKeNhaCungCapTheoDoanhChiFrm thongKeFrm = new ThongKeNhaCungCapTheoDoanhChiFrm();
        thongKeFrm.show();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void HoaDonNhapTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoaDonNhapTableMouseClicked
        int index = HoaDonNhapTable.getSelectedRow();
        TableModel model = HoaDonNhapTable.getModel();
        String tongTien = model.getValueAt(index, 2).toString();
        String soLuong = model.getValueAt(index, 3).toString();
        JOptionPane.showConfirmDialog(rootPane, "tongTien = "+tongTien+", soLuong = "+soLuong);
    }//GEN-LAST:event_HoaDonNhapTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListNhaCungCapFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListNhaCungCapFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListNhaCungCapFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListNhaCungCapFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ListNhaCungCapFrm(list1, list2).setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ListNhaCungCapFrm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(ListNhaCungCapFrm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable HoaDonNhapTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel note;
    private javax.swing.JLabel tieuDe;
    // End of variables declaration//GEN-END:variables
}
